vod_path:
  - ./vod
image_path:
  - /image
delete_empty_dir: true
delete_hidden: false
interval: 100ms
free_percent: 10
dry_run: true
debug: true
db:
  db_host: 192.168.6.190
  db_port: 6868
cpuprofile: ''
server_port: 8089